### ISSUE TITLE
Support for Powerpoint

### ISSUE THREAD

**Issue by Hi-there-how-are-u** [AntonyCorbett/OnlyM#128]
Lately we had some speakers with powerpoints among them our circuit overseer.
I am guessing this is not possible but I wanted to ask since we have always problems with the PPT-files.
I can hint them to use PDF instead... :)

**Comment by TizianoNoto** [comment]
Yes, PDF is the best solution. Different setups (even different versions of Powerpoint) can lead to unexpected results.

Anyway, you can set a specific monitor for full screen presentations in MS Powerpoint and LibreOffice Impress. Of course you need to manually click on the JWL media window icon afterwards. Let me know if you need help.

**Comment by TizianoNoto** [comment]
Yes, PDF is the best solution. Different setups (even different versions of Powerpoint) can lead to unexpected results.

Anyway, you can set a specific monitor for full screen presentations in MS Powerpoint and LibreOffice Impress. Of course you need to click on the JWL media window's icon afterwards. Let me know if you need help.

**Comment by AntonyCorbett** [comment]
@Hi-there-how-are-u Good topic. Personal view only - ppt is akward since in the context of a cong. meeting (which is our main focus here) the presentation should be controlled - not by the speaker - but by the A/V desk. And if a speaker is using ppt it's probably because he has some triggered bullet points, animations etc.  Currently the instruction is to use simple images only. So, if that's all the ppt contains then let's just have a sequence of images please! If it's being used for anything more sophisticated then you might just say "sorry, it's not supported".

I don't have plans to present ppt files.

**Comment by timjobutler** [comment]
@Hi-there-how-are-u @TizianoNoto Prior to coming to the hall, if the speaker/CO uses the Save As function, either one or all the slides can be exported as images. Attached is the image file types that can be saved to in MS PowerPoint along with export option.

With the slides exported as images, they can be handled in OnlyM very easily.

Hope this information is helpful

![ppt-save-as-file-types](https://user-images.githubusercontent.com/37101212/49623046-16031b80-fa20-11e8-9fb5-102378708574.jpg)
![ppt-export-options](https://user-images.githubusercontent.com/37101212/49623054-1dc2c000-fa20-11e8-8e94-726b86b6cdef.jpg)

**Comment by Blann** [comment]
The option we usually use in the context of a congregation meeting (i.e. when JW Library is running) is what @timjobutler described, for the simple reason that OnlyM co-operates with JWL. Animations and transitions are lost when doing this, but I think it's very rare you'd get something that elaborate for use during a meeting. Many brothers just have one image per slide.

Outside of meetings, we just display straight from PowerPoint.

As an aside, to me, PDFs are unsatisfactory for this as well because the presentation is never seamless – there'll always be some positioning, resizing, zooming etc. To my mind, seeing _any_ manual interaction with the media display(s) on the part of the operator defeats the object of a smooth presentation and is needlessly distracting. But that of course is a personal opinion.

**Comment by mbrakutt1** [comment]
@timjobutler Why not export your slides with transitions / animations as a video / mp4. Of course you can you can set the durations of the each slide in this case your images to let's say 4 seconds and your transition lasts 2 seconds with this maybe OnlyM can incorporate some sort of "play to frame" or play to chapters (like what VLC has) so let's say we have 4 chapters, 4 images so you can select in OnlyM your desired frame to stop to (maybe like scrubbing) so when you press play it plays the first chunk and stops and remains on the display somewhat like the sideshow feature.

Just an idea not sure if it's possible.

**Comment by AntonyCorbett** [comment]
There is a convoluted method for presenting PowerPoint via OnlyM. Use the PowerPoint "File | Share" command to share the presentation. Add the resulting Url in OnlyM as a web shortcut.

**Comment by Hi-there-how-are-u** [comment]
Great, thank you Antony! Luckily this född nu occur often. Most have images...
