### ISSUE TITLE
JW Library Year Text Disappears

### ISSUE THREAD

**Issue by delmar5930** [AntonyCorbett/OnlyM#186]
**Describe the bug**
When we display an image in OnlyM, then close the image, the year text in JW Library disappears. [The JW logo remains, only the text disappears]. If we redisplay the same image in onlyM, then close out, the text in JW Library reappears. (The text disappears every other time we display an image in onlyM).

(Side note: Our hall has two local accounts in Windows (French and English). The French side does not have this issue. We have uninstalled and reinstalled both JW Library and onlyM, however the issue remains the same on the English side.)

**To Reproduce**
1. open JW Library
2. open onlyM
3. display image
4. close image

**Expected behavior**
After the image is closed, the text in JW Library should reappear.

**Desktop (please complete the following information):**
 - Windows version: Windows 10 Pro
 - Other important information about your environment: This is a fresh installation of Windows 10... new PC. All current updates have been install.

A brother set this computer up at home, created the local accounts, installed programs and downloaded media. Everything worked for him at home. The French side continued to work once it was hooked up at the hall, however for some reason the English local account does not. We have also changed the languages on the English side to French and Spanish and have the same issue.

Again, we can't reproduce the issue on the French local account. We have checked the settings of both accounts and they are identical. We have also tried changing the fade style, fade speed, and cache images options.

We have also tried creating a fresh local account in windows and reinstalling JW Library and onlyM.

(Thank you for your assistance and your work on this program.)

**Comment by AntonyCorbett** [comment]
@delmar5930 

See #58 

It's been observed by others. And it can happen even if you just open and close the JWL media window from the taskbar. I believe it's either a bug in JWL or in the graphics driver. You might try updating the latter.

**Comment by jmccormic** [comment]
We are having the same issue. It seems that every other time we click an image we lose the "years text." Only set up as one language. Problem is with and without using OnlyT. Fresh download of both did not resolve issue. Unable to use OnlyM currently due to this issue. Having to stay with SoundBox. Please offer any suggestions.

**Comment by AntonyCorbett** [comment]
@jmccormic as noted above, the issue appears to be caused by a bug in JWL or in the graphics driver. Have you updated the graphics driver? That has fixed it for some. I know this isn't particularly useful, but the code that restores JWL media window in SB and OnlyM is the same - we just identify the JWL main window and bring it to the foreground.

If you can reproduce the issue fairly easily I wonder of you would try to reproduce it without OnlyM as follows:

1. Launch JWL and year text display.
2. Drag any open window (e.g. Notepad) over the year text display (this will cause JWL to minimize the year text window).
3. Move the Notepad window off the 2nd display and restore the year text by clicking the JWL taskbar icon and selecting the year text window.
4. Repeat 2 and 3 until the year text displays without the text!
