### ISSUE TITLE
Resize thumbnails and box size. Timer

### ISSUE THREAD

**Issue by jsquiggz** [AntonyCorbett/OnlyM#25]
We have a need for 3 apps open on screen at  one time due to the fact that during the meetings the programme is on the screens and we have to flick between camera and jw library etc using a switcher app. The size of the only m app means that we struggle to get everything to a useable size.

Also, can the meeting start countdown timer be intergrated into only-m again because of oir set up, we can only display the meeting countdown timer (only-t) to a rear screen.

Thank you for all your hard work, we really appreciate it, it makes like much simpler every meeting

Jon
Chelmsford. Essex

**Comment by Blann** [comment]
As you won't be using OnlyM and JWL at the same time, why not just have OnlyM open in that location?

Lack of a countdown on the media monitor(s) is deliberate I believe - direction is to display the yeartext from JWL before the meeting and it's difficult, if not impossible, to overlay anything (e.g. a countdown) on it because it'll minimise itself if anything opens on the same screen.

**Comment by omaha4** [comment]
Also, I have a suspicion that you are using an ATEM TVS as a switcher, hence using the ATEM switcher software. Here in the US, the direction is to us switchers with physical buttons, because they are easier to operate. If this is not feasible, an app like Strata Lite for iPad or one of the free alternatives for Android could be a good route until you are able get a switcher that is not software dependent.

**Comment by jsquiggz** [comment]
Thanks Antony,

That makes sense, we wanted to limit the amount of closing and opening
going. I'm sure we can work around it somehow.

Thanks again
Jon
