### ISSUE TITLE
Media Monitor MonitorName  too general

### ISSUE THREAD

**Issue by Xachman** [AntonyCorbett/OnlyM#27]
When I was switching monitors I noticed they are all named "Generic PnP Monitor".   After opening the project and looking at the monitors variable in the GetSystemMonitors method it looks like we have some access to more specific naming for the ComboBox.  I would love to have the monitor number appended to the name.  I see that DeviceName is available could we use that with string replace to get the display number?

**Comment by AntonyCorbett** [comment]
@Xachman Where possible, the more descriptive names are used. If you follow the code you'll notice why the "generic" names are used in some cases.

**Comment by Xachman** [comment]
I see DeviceString is used when available but in my case I have a 4 monitor setup and my options are.  

- None
- Generic PnP Monitor
- Generic PnP Monitor
- Generic PnP Monitor
- Generic PnP Monitor

I dont know what the cases are that the user would want the DeviceString vs the DeviceName since DeviceName will allways be more specific.

**Comment by AntonyCorbett** [comment]
If you examine the Windows Graphics Display Properties dialog, under the Monitor tab you'll see that the Monitor type is specified as "Generic PnP Monitor". This is the value that OnlyM uses. It may be that you can update the monitor driver rather than using Microsoft's default generic one. The difficulty associated with using the Device name, e.g. //DISPLAY1 or the numeric element of it is that these may not be consistent from one day to the next because the video driver may not enumerate the devices in the same order at each boot.

**Comment by Xachman** [comment]
Ill checkout what installing manufactures drivers do and get back to you.
