### ISSUE TITLE
Onlym issue

### ISSUE THREAD

**Issue by JBHays** [AntonyCorbett/OnlyM#283]
Loaded the Disaster training media into the Onlym  documents file. The 32 files are jpg files for the training session. We have a Dell Inspiron laptop connected to our Audio/Video system at our Kingdom Hall. When we press the play button on the program the slides pulse off and on the Vizio 70 inch screens. I have deleted the program and reinstalled it with no success. We also had the 4 video that are tied to the training session in the program documents file but I took them out but problem continued. Any ideas what the problem might be? Thank you.

**Comment by AntonyCorbett** [comment]
Some questions:

1. What version of OnlyM?
2. Does the image fade in then out then in again? Does this continue indefinitely or happen only once? Does the image eventually remain visible or invisible?
3. Do you see the same effect when using the primary display for media rather than the TVs?
4. Does turning the 'fade' setting on or off make any difference?

**Comment by AntonyCorbett** [comment]
@JBHays Closing now because there is no response. Please reopen if needed.
