### ISSUE TITLE
Stuttering on MP3 and MP4

### ISSUE THREAD

**Issue by its-markk** [AntonyCorbett/OnlyM#3]
Tried using OnlyM 1.0.0.7 to play an MP3 of the John 4:43-54 reading, and also to play the Song #1 MP4 file.  The reading file would stutter when it looks like maybe Windows was doing something else with the C: drive.  The Song would crackle and sometimes stutter.

**Comment by its-markk** [comment]
We are using on of the small recommended ASUS media computers.

**Comment by AntonyCorbett** [comment]
@its-markk Please check that the video driver is up to date.

**Comment by XionTech** [comment]
@its-markk When you say the recommended Asus computers, do you mean something like the VM42? What other applications were running at the time?

**Comment by its-markk** [comment]
Yes, the VM42 model. All I had running for the test was JW App and OnlyM,
since needed to make sure that the year text screen would work as expected
and the OnlyM would work too.

I first noticed it when I put a copy of song #1 and tried playing it.
Initial took a long time to start playing, then was ok. After a little bit
of time, noticed the crackling and stuttering.

**Comment by its-markk** [comment]
Some side info.  Neighboring KH also has an ASUS VM42, but with 2 differences.
Ours is already running Window 10 v1803, theirs is actually updating to that right now.
Ours has the factory hard drive still, a WD Blue drive.
Theirs has a replacement hard drive, a WD Black drive, which has better performance than the Blues.
For them, early on, with Soundbox, they would have an issue with downloaded videos pausing or stuttering.  Could not get any diagnostics to show there was any issue, and hard drive checks and advanced diags all said things were OK.  Other drivers up to date.  Educated guess and some hoping, replaced the factory WD Blue with a WD Black.  No issues since then.
Just loaded OnlyM on their computer and they don't have the stuttering.  Will test theirs again after the Windows update.

**Comment by XionTech** [comment]
Those VM42 haven't been ideal but if tweaked just right it should be able to manage. If you aren't able to get it by next week (I'll be away until then), I can boot up a VM42 I have and work through it with you. 

Some initial thoughts: Do you have any antivirus going?  Is the power in balanced or performance mode? All updates applied with other non essential windows features turned off?

**Comment by its-markk** [comment]
There is no additional anti virus, just the built in Windows security.
After the 1803 Windows update, I'll have to check to see what Windows stuff
is enabled; so nice of Microsoft to re-enable disabled items. And I'll
track down other sure updates this weekend. Thanks.

**Comment by XionTech** [comment]
I actually noticed stuttering today with some tests if I do anything else on the computer. And that was with a heavy duty machine with Geforce 1060 so I'm beginning to wonder about setting the Application priority.

**Comment by its-markk** [comment]
The other KH Windows update 1803 finished on their Asus VM42 with a better
hard drive in it. They copied Song#1 in to the app and it started to
crackle and stutter, then even more so if doing something else on the
computer like exploring folders and files.  They then tried playing a song
form the JW app and said was not as bad cracking and stuttering.

They use Windows Media Player for their songs, and that worked fine.

I know on VM42 with the standard hard drive and our internet will every
once in a while millisecond glitch on playing a song from the JW app.

I can try adjusting the priorities for the app to see if that makes any
difference.

**Comment by AntonyCorbett** [comment]
@its-markk @XionTech Please would you test v1.0.0.8? I have made some minor improvements to playback performance.

**Comment by AntonyCorbett** [comment]
@its-markk @XionTech v1.0.0.9

**Comment by its-markk** [comment]
Will test latest version late tonight.

**Comment by TechMan88** [comment]
Great Media Player, i have 1 to 2 stuttering also on videos im testing on the caleb sofia short videos...
I down load the latest version i notice i have less stuttering when i switch to warning im trying out diff settings

**Comment by AntonyCorbett** [comment]
@its-markk @XionTech @TechMan88 I have updated to use ffmpeg 4 as of version 1.0.0.11

**Comment by AntonyCorbett** [comment]
The rendering is still fairly CPU intensive (owing to the use of ffmpeg and largely software decoding (GPU is not used much). Since the focus is on image display, this will have to go on the back burner for the moment. I'll keep the issue open.

**Comment by its-markk** [comment]
Thank you for your work on this.

**Comment by fluffypony** [comment]
@AntonyCorbett on smaller devices (eg. anything with a Celeron or a Atom processor) you basically *have* to offload to the GPU for decoding. Even on faster processors (Core i3) you have to offload like 1080p and above.

I'd hazard that [DXVA2 should have pretty broad support](https://trac.ffmpeg.org/wiki/HWAccelIntro#DXVA2) (DX9 and above) if you plan on targeting Windows only with the Only* apps.

**Comment by AntonyCorbett** [comment]
@fluffypony excellent link - I will investigate further, Thanks.

**Comment by AntonyCorbett** [comment]
@fluffypony looks like the ffmpeg binaries I am using already include dxva2 (https://ffmpeg.zeranoe.com/builds/)

**Comment by fluffypony** [comment]
@AntonyCorbett this is, admittedly, out of my wheelhouse, but I think that means the build merely supports DXVA2. You still need to enable it so that it tries to use it for the media playback, as it's off by default. On command-line ```ffmpeg``` that means passing the ```-hwaccel``` CLI flag; in code I'm less certain, but the [https://trac.ffmpeg.org/wiki/HWAccelIntro](HWAccelIntro) page I linked earlier might provide some input.

**Comment by EthAsk** [comment]
@AntonyCorbett Have you had any recent luck with this issue at all?

**Comment by AntonyCorbett** [comment]
@EthAsk No. Unfortunately, the libraries that I use are unable to make use of dxva2 yet.

**Comment by gonzo041** [comment]
Is there an estimated date of solution for the problem of stuttering?

**Comment by AntonyCorbett** [comment]
@gonzo041 Sorry, no. The rendering technique currently requires a moderately powerful CPU.

**Comment by gonzo041** [comment]
Sorry for my ignorance but, because with SOUNDBOX does not that error occur?

**Comment by AntonyCorbett** [comment]
@gonzo041 SoundBox has 3 rendering options - each uses a different technique for decoding and rendering the video. Some are slower than others but may offer better quality or wider compatibility. OnlyM uses a single rendering technique (which incidentally is not one of the SB options). I chose it because it does not require 3rd-party codecs and should not depend on the capabilities of the video card. However, the downside (as you have found) is that it uses the main processor (CPU) to do most of the work rather than the graphics card (GPU) requiring a reasonably well-specified machine. I will probably add one or more additional rendering modes eventually but I don't have a timeline for it. Thanks for your feedback - much appreciated.

**Comment by 2OfratellO** [comment]
We've been having the same problem.  Foreign language and we hoped to use OnlyM for videos when we have to download the public talk for Sunday.  (Back to iTunes for now.) Is there a place I can get an update when the new release is ready?  Thanks for your attention to this "hiccup".  The rest of the design is really great.

**Comment by AntonyCorbett** [comment]
@2OfratellO this is the place to get updates. Just subscribe to notifications on this issue.

**Comment by AntonyCorbett** [comment]
@2OfratellO you can try lower resolutions which will help.

**Comment by Blann** [comment]
Just a question regarding this - is making the OnlyM process higher priority likely to make any material difference to rendering performance?

**Comment by AntonyCorbett** [comment]
@Blann @2OfratellO @gonzo041 @fluffypony @EthAsk @its-markk @XionTech 
The latest draft release adds the "Media Foundation" rendering engine (see Settings, Video).

**Comment by AntonyCorbett** [comment]
@Blann the process already has "above normal" priority. You can experiment by altering the priority in the Task Manager Details tab. Please try the latest draft release (using Media Foundation rendering which is less CPU intensive).

**Comment by 2OfratellO** [comment]
Grazie.  We’ll try it out this afternoon.

Russ

**Comment by Blann** [comment]
Can confirm that the performance issues are solved.

I hadn't noticed before, also present in SoundBox - MF seems to increase the brightness of videos (blacks appear grey); is that just a peculiarity of the rendering engine?

**Comment by danielthorley** [comment]
It has fixed this issue on our PC too. Thanks Antony!

**Comment by omaha4** [comment]
The stuttering has been fixed on my Surface Book as well. There is, however a noticeable increase in saturation that did not seem to be present on SoundBox when using WMF. At this time, this would prevent me, along with issue #28 and playlist oriented playback (as opposed to folder oriented playback) from recommending OnlyM on the same level as VLC (being able to open a file and have it open in a desired program simplifies training when you are sharing a KH).

**Comment by AntonyCorbett** [comment]
@omaha4 thanks for feedback on this. The saturation issue has been reported but I can't reproduce on any systems here. I suspect it may be dependent on video card, Thanks for trying OnlyM, Sadly, I don't think it will ever meet your stated requirements.

**Comment by Blann** [comment]
Realise we’re getting off the issue here, but post-SoundBox, I would say OnlyM is superior to VLC for handling both images and videos in a congregation meeting setting for the simple reason that it co-operates with JW Library. I don’t think the value of that should be underestimated for those who were used to the integration that SoundBox afforded, and I think that’s who OnlyM is really designed for (I’m sure Antony will correct me if I’m wrong).

**Comment by 2OfratellO** [comment]
Great job. I haven’t tried it yet. But, it does what you’ve said.  Great job.   Thank you for supplying this FOR FREE! I think some may forget how generous you’ve been.  Thank you again, brother.

Russ

**Comment by omaha4** [comment]
@Blann Yea, don't mean to stray off topic either, but I do have to follow up. I think that one thing that gets lost in all this is, all of our circumstances vary. In one way or another, all of our KH's circumstances vary. 

For example, in our KHs case, when we train for AV, we just aren't training for JW Library or Sound box, or VLC, we are training basic computer skills, skills that I've taken for granted greatly because I had the opportunity  learn off of MS-DOS, Apple 2, early 90's MAC, learned to type off of Windows for Work Groups, survived the Windows x86 era (Win95-Me) and so on. Now, its my turn to pass it on to those older than me, and to do so patiently. When I train on AV, I have to consider my audience. This applies to which programs I use to show extra videos and pictures, doing so knowing that if they mess up, they can learn and go on and use the knowledge elsewhere, such as JW.org. This is a big reason why #28 makes so much sense to our circumstances, it's Windows/ Mac OS 101. I have to remember, the ones I am teaching, they have no idea what GitHub is or what it is used for. Training like this keeps us humble, and busy.

Another example is a post I seen on Soundbox Facebook that is a few days old, but I refuse to have a account there so I didn't respond. This individual's KH doesn't have internet. Nobody's fault, just in some places, the internet stinks. This causes several problems. JW Library can't be updated. Virus definitions are not up to date, leaving them potentially vulnerable to USB sticks and there potentially undisciplined use. What would our advice to this person be? Soundbox? VLC with it's powerful library support for easy referral to the song book? A mobile laptop? How many congregations do they have? Is a MAC with VLC or Playback Pro  (and the MAC's sandboxing features) a better fit for their circumstances? You get the idea.

The point is, it is so easy to make broad assumptions that we lose sight that everyone's circumstances are different. No ones fault. That's just the way it is in this old world.

**Comment by Blann** [comment]
Just a little local update on the issue - I think it will be a compromise whichever rendering engine we choose to use. Media Foundation is less resource-intensive but Ffmpeg does look better (using MF videos look somewhat 'washed out', as if the luminance is not quite right - more noticeable on a projector screen). The audio level is also slightly lower when using MF which I have no explanation for. Suspect one or both of these issues might be related to our setup but would be interested to know if anyone else experiences the 'greying' effect when using MF.

**Comment by AntonyCorbett** [comment]
@Blann regarding "washed out" video when using Media Foundation mode, it has been observed and reported before but I haven't been able to reproduce the issue. Perhaps it is dependent on video card. It would be useful to know if the same is experienced when using SoundBox in media Foundation mode.

**Comment by AntonyCorbett** [comment]
@Blann have aded a new issue #45

**Comment by drmeyer** [comment]
Anthony,  We have the same issue with stuttering.  I would like to try the draft release that you mentioned using the "Media Foundation " rendering engine,  but I'm a total loss as to how to find the download.  The only download I find is the latest ...25.  Please point me to correct location.  I have reinstalled 1.0.0.25 and there is no option to select "Media Foundation" rendering engine.

Thank You

Have attached 
[log-20180825.txt](https://github.com/AntonyCorbett/OnlyM/files/2321130/log-20180825.txt)

**Comment by drmeyer** [comment]
Thanks, Got it.  Works much better with "Media Foundation" rendering.  Much
appreciation for the resource..


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
08/25/18,
8:49:12 PM

**Comment by AntonyCorbett** [comment]
Closing now that Media Foundation support is included
