### ISSUE TITLE
OnlyM Slide Manager Desktop Icon Moves with Updates

### ISSUE THREAD

**Issue by GrahamR-AU** [AntonyCorbett/OnlyM#302]
**Describe the bug**
I always place the OnlyM Slide Manager desktop icon directly to the right of the OnlyM icon manually. Every time I install an update to OnlyM the OnlyM Slide Manager icon moves to the LHS of the screen below all other icons, whereas the OnlyM desktop icon stays where it was.

**To Reproduce**
1. Intsall an OnlyM update (or reinstall OnlyM)

**Expected behavior**
I would like the icon to stay where I put it

**Desktop (please complete the following information):**
 - Windows 10 Version 1903

Just a minor annoyance!

**Comment by AntonyCorbett** [comment]
@GrahamR-AU Both application icons will be moved on installation (and this will be true of other applications you upgrade too). You don't see the OnlyM icon move because it's already in the "lowest" position. This happens because the installer performs a complete uninstall first followed by an install.
