### ISSUE TITLE
Automatic 2nd Monitor Auto-Detection

### ISSUE THREAD

**Issue by jomast** [AntonyCorbett/OnlyM#32]
Depending on the order that our computer, monitor, and TVs are turned on, the TVs in our hall might be located at `\\.\DISPLAY1` or `\\.\DISPLAY2`. (My research has shown that this behavior is baked into the hardware of the graphics card) When this changes, the settings in OnlyM must be adjusted to compensate. (While we try to be strict about the order of things, but it's very difficult to control with three congregations)

JW Library has a simple *play video on second display* setting and it automatically figures out which display is the "second". It would **very** helpful to have similar behavior in OnlyM.

I would imagine the logic would be to determine the display that the OnlyM app window is in... and use the other one as the "second display".j

**Comment by AntonyCorbett** [comment]
@jomast thanks for feedback. The situation's a little more complicated because OnlyM must work with > 2 monitors (many use a third monitor for timing). OnlyM should also be able to select the primary monitor in order to test playback, etc. (JWL always uses the monitor that appear directly to the right of the primary monitor in Windows Display properties.) If you are seeing the device names e.g. "\\.\DISPLAY1" in your monitor selection list (as appears to be the case) this means that OnlyM has reverted to a simple method to distinguish displays because the video driver has been unable to return correct information using the Windows EnumDisplayDevices API. When this happens then you see the behaviour you describe - displays may be enumerated in a different order on each boot (unless you leve devices physically connected and in standby mode). There are a few options as follows:

1. Update your video driver to see if it correctly reports the monitor names (in which case the monitor list will show names rather than device designations).
2. Leave monitors on standby and check that the video driver consistently enumerates them in the correct order.
3. Use third-party software (e.g. https://www.nirsoft.net/utils/multi_monitor_tool.html) to manage multiple monitors.
4. Use a EDID hardware device to maintain an identifiable "connection" to your monitors even when they are turned off.

Hope this helps.

Kind regards
Antony
