### ISSUE TITLE
Always On Top

### ISSUE THREAD

**Issue by Blann** [AntonyCorbett/OnlyM#35]
In the current release the window stays 'always on top' after display is ended, even if that option is unchecked in Settings. Manually cycling the option removes the flag so it's as if it's just not being removed automatically when display ends.

**Comment by TizianoNoto** [comment]
Can confirm.
I successfully replicated the issue down to release 1.0.0.20. Version 1.0.0.19 does not have this problem.
Changing the media display or toggling the "always on top" checkbox solves it until another item is played.

I also notice that switching the media display also triggers the permanent backdrop, even if the checkbox is disabled. However, starting and stopping any media makes it revert to the expected behavior.

**Comment by AntonyCorbett** [comment]
Fixed #35
@TizianoNoto have raised #36 for the other issue.
