### ISSUE TITLE
Volume problems with screen sharing in ZOOM

### ISSUE THREAD

**Issue by KovalevArtem** [AntonyCorbett/OnlyM#354]
After updating ZOOM to version 5.2, the video volume became much quieter. (This may not be related to the update).

But in any case, when using OnlyM, the sound is much quieter than (for example) when using VLC. Also when using VLC, I can freely and conveniently adjust the playback volume ...

How to solve this problem?

_Windows 10 2004 x64
OnlyM 1.6.0.5 only_

**Comment by AntonyCorbett** [comment]
@KovalevArtem Please use the Windows Volume Mixer to adjust the OnlyM playback volume.

**Comment by Minakah** [comment]
I am new at this Github, so I hope I am doing this right?
I notice this is closed but I have the exact same issue which is a bit annoying since we on a regular basis use prerecorded public talks, and I prefer to use OnlyM over VLC due to how nicely it works with JWL.

I have all volumes maxed out but it still is significantly lower, in fact I even measured (with my iPhone) if I get 83dB avg for a a given video from JWL, it was 74dB from the very same video file when played over OnlyM. I have tried with a variety of programs like Boom 3D but it doesn't seem to increase the output I need, I also don't actually have any physical speakers connected to the "Media PC" as we call it, I hear everything through my Mac just as everyone else, that way I know if something's off or low or high.

Thank you for any suggestions!!

**Comment by AntonyCorbett** [comment]
@Minakah Just checking that you have set the OnlyM volume in the Windows Volume Mixer. Launch OnlyM then right-click the audio icon in the system tray, select Volume Mixer.

**Comment by Minakah** [comment]
> @Minakah Just checking that you have set the OnlyM volume in the Windows Volume Mixer. Launch OnlyM then right-click the audio icon in the system tray, select Volume Mixer.

Yes it is all maxed out in Win audio mixer indeed.

**Comment by AntonyCorbett** [comment]
OnlyM volume cannot be adjusted within the app - it is set at unity. All things being equal it should match the output volume of JWL (it does on my test systems). Sorry I can't be more helpful. Perhaps someone else can comment further.

**Comment by Minakah** [comment]
> OnlyM volume cannot be adjusted within the app - it is set at unity. All things being equal it should match the output volume of JWL (it does on my test systems). Sorry I can't be more helpful. Perhaps someone else can comment further.

Thanks, it USED to be, and I didn't know why it changed but the above comment about Zoom update started to make sense, that's why I thought I'd bring it up. Maybe I'll see if I can locate the older version of Zoom and try to "downgrade" to see if that really is what changed it.

**Comment by AntonyCorbett** [comment]
@Minakah Some questions:

1. How does the volume compare on the media PC itself (i.e. not via Zoom)?
2. Are you using the zoom "Original sound" option?

**Comment by Minakah** [comment]
The PC has no speakers connected at all, it easier that way as I run a Mac and this Windows (only for JWL and zoom meeting purposes) at the same time. I've had headphones hooked up but never any actual speakers, it doesn't have any in it.

As for the zoom setting will have to check it's bed time (long past actually) here now...

**Comment by AntonyCorbett** [comment]
So how does the relative volume (OnlyM vs JWL) compare on the media PC?

**Comment by Minakah** [comment]
> So how does the relative volume (OnlyM vs JWL) compare on the media PC?

As you notice in my initial post almost 10dB difference on the exact same file (granted one was downloaded from the JW org website while the other was through JWL) played on JWL vs OnlyM, based on this app:
https://apps.apple.com/us/app/decibel-accurate-db-meter/id1130936133

**Comment by Minakah** [comment]
> @Minakah Some questions:
> 
> 1. How does the volume compare on the media PC itself (i.e. not via Zoom)?
> 2. Are you using the zoom "Original sound" option?

In regards to "Original sound", perhaps I should add that this PC does NOT have any mic NOR speakers hooked up?

**Comment by AntonyCorbett** [comment]
@Minakah Did you state that you had headphones attached to the media PC? I'm willing to accept that you are hearing a difference in volume via a Zoom client at the receiving device, but I'd like to establish whether there is actually a difference in volume in the sending device.

**Comment by Minakah** [comment]
I have had headphones plugged in at times but don't usually have anything audio in or output connected. I'll do some testing with actual speakers to the actual PC and get back to you thanks.

**Comment by FrancescoCavallaro** [comment]
**@AntonyCorbett** the problem was verified by me on several computers with speakers.
One way to solve it is to activate the Windows "Loudness Equalization" option.
Not all devices have this option.
There are several guides on the web.

Enable Loudness Equalization
1. Press the Windows logo key + S shortcut.
2. Type 'audio' (without quotes) into the Search area. ... 
3. Select 'Manage audio devices' from the list of options.
4. Select Speakers and click on the Properties button.
5. Navigate to the Enhancements tab.
6. Check the Loudness Equalizer option.
7. Select Apply and OK.

===ITALIANO===

il problema è stato da me verificato su diversi computer dotati di casse acustiche.
Un modo per risolverlo è quello di attivare l’opzione “Loudness Equalization” di Windows.
Non tutti i dispositivi dispongono di questa opzione.
Sul web si trovano diverse guide.

Abilitare Loudness Equalization
1. Tasto Windows + S.
2. Digita 'audio' nella campo di ricerca... 
3. Scegli 'Impostazioni audio' e dopo "Pannello di controllo audio".
4. Seleziona "Altoparlanti" e il pulsante "Proprietà".
5. Seleziona la scheda "Enhancements".
6. Metti la spunta su "Loudness Equalizer".
7. Applica con "OK".

**Comment by KovalevArtem** [comment]
@FrancescoCavallaro Do you propose to do this?
![image](https://user-images.githubusercontent.com/36500228/99146523-04a1ff80-268a-11eb-89df-798892c5367d.png)

**Comment by FrancescoCavallaro** [comment]
**@KovalevArtem**, Yes. on my computers, this option solved the problem.
![1_cr](https://user-images.githubusercontent.com/74300780/99154858-41ceb780-26b3-11eb-8d11-2806fca38233.jpg)

**Comment by FrancescoCavallaro** [comment]
![2020-11-14_193802](https://user-images.githubusercontent.com/74300780/99154878-6c207500-26b3-11eb-9e28-445b7c266524.jpg)
