### ISSUE TITLE
Can not close onlym after screen-share

### ISSUE THREAD

**Issue by impac1** [AntonyCorbett/OnlyM#379]
Ok, let's get this out of the way: I am not very smart using & understanding technology. That being said, even scarier, I'm the video conference organizer, so you can imagine our plight. I have been around Sound Box (and miss it still). I use my laptop for Zoom & to play the media, so I only use 1 screen. I try to use Only M for images 7 videos but after viewing item things seem to lock up, I cannot get to the Only M box to close the image, and it takes a long time to get everything back  to the Zoom meeting. Is there something I am missing ( okay, that is a litotes)? Thank you,

**Comment by AntonyCorbett** [comment]
> things seem to lock up, I cannot get to the Only M box to close the image

Please would you elaborate? Are you displaying media full-screen (so that the media obscures the main OnlyM window) or in a small window? Is it simply a matter of being unable to navigate back to the OnlyM window or are the OnlyM buttons unresponsive? Please provide as much information as you can.

**Comment by mjameswh** [comment]
@impac1, here are some suggestions for you:

First, if at all possible, you should definitely try to have a second monitor when doing Zoom+OnlyM. Most laptops have a HDMI output connector. If your computer has such a connector, then you can plug it to a regular TV. That's free, and yet, that will make things much more easier for you.

Now, if connecting a second monitor is not possible, then open OnlyM's settings and make sure that option "Windowed" is checked. Otherwise, OnlyM's media window will take the full screen and might prevent you from accessing the OnlyM media list window...

If you still need help, would it be possible for you to take some pictures of your computer's screen, for example using your cell phone or a tablet, then post these pictures here? You know, they say one picture is worth a thousand words...

**Comment by AntonyCorbett** [comment]
@impac1 Closing for now as no further response. Please feel free to reopen if necessary.
