### ISSUE TITLE
How do you, or can you add... and order video/image function?

### ISSUE THREAD

**Issue by robertkjr3d** [AntonyCorbett/OnlyM#386]
There appears to be no way to order the videos/images after they have been dropped into OnlyM.
You should be able to drag them up and down, or move them with an arrow function.

Maybe there is a unintuitive function that does exist, I just haven't found it?

What appears to be the case, is that it orders them alphabetically I think.  And you have no say in the matter after they have been dropped on.

**Comment by yjenb** [comment]
Hey,
I just use this way of ordering the files. I'm adding a 3 digits-prefix to the files to get them in the right order. And to make sure, I could add additional media files requested, I use an interval of 10. So my prefixes are: 010, 020, 030, etc.

![image](https://user-images.githubusercontent.com/53382065/120080076-83efa180-c0b7-11eb-9611-1f42da22d063.png)

I love this way to do it.

**Comment by AntonyCorbett** [comment]
@robertkjr3d You are right. Please see the Wiki under Operation => General. There are no plans to provide manual ordering within OnlyM itself.

**Comment by robertkjr3d** [comment]
hmm... I've been using the software for a while, and now during zoom-land even more, even sometimes for non-jw sharing.  Its such a great tool.  But have often wanted to move stuff around.  Being a programmer, it would seem that ordering wouldn't be that hard to add. Maybe I'll look at the source and put it in myself and recompile.

**Comment by AntonyCorbett** [comment]
@robertkjr3d Thanks. A PR would be most welcome if you come up with a solution that are you willing to share. Some things we'd do well to consider:

1. How manual ordering is persisted across sessions (we would not want to lose the ordering if the application is closed and restarted).
2. Whether persistence is maintained per-folder, so that a change in Settings => Media folder and back again retains any manual established ordering.
3. How newly added files are inserted into a manual order.
4. How to visually indicate if manual ordering is in place.
5. Whether there should be a command to revert to native ordering.
6. The need to ensure that the special "Blank Screen" item remains at the top of the list (cannot be reordered).
7. The need to either prevent or properly support manual ordering during playback.
8. How hidden items are accommodated during manual ordering.

You may think of other considerations too. I appreciate any assistance,

**Comment by robertkjr3d** [comment]
>>6 oh i was not familiar with 'blank screen', until you mentioned it, then looked in settings.
I've only used JW-Library compat mode.  I have noticed many known and unknown tend to knock the library-screen off its spot on the 2nd-screen.  But I'm sure that's another 'issue' somewhere on here your dealing with.  And not entirely your problem.

All of your items:... I'm impressed with the quick thinking of all of the items to take into consideration if I was to back-share it.

**Comment by AntonyCorbett** [comment]
@robertkjr3d Closing now, but please reference this issue if you decide to create a PR. Thanks for your feedback.

**Comment by robertkjr3d** [comment]
I know its been 5 years, but I'm out of work now, and I've finally got time to do this. The program would still be better for it I think. Unless you see that someone else is in the middle of it.

**Comment by AntonyCorbett** [comment]
@robertkjr3d thanks for picking up this thread again. Please feel free to take this on. AFAIK, no one else is. You will have your own ideas, of course, but here are some considerations based on an analysis of the current code by Claude (and my comments in square brackets):

**1. Core mechanism**
Add a mode flag (Automatic / Manual), read by SortMediaItems() (OperatorViewModel.cs:1201):
- Automatic → unchanged: compute SortKey from filename, sort as today.
- Manual → skip the alpha-sort; apply the persisted order instead.

**2. Persistence**
Store an ordered list of filenames per effective folder-set (root MediaFolder + whatever DatedSubFolder is active), following the mediaOptions upsert pattern in DatabaseService.cs:290, or as a simple ordered List<string> similar to RecentlyUsedMediaFolders if you'd rather keep it out of SQLite. Scope this per folder/date, not globally — a stored order for one day's file set has no guaranteed relationship to another day's, given the calendar-folder feature changes membership daily.

[I think I'd prefer to see this kept out of the SQLite database, so the implementation of persistence could be in OptionsService similar to RecentlyUsedMediaFolders]

**3. New/unrecognized files in Manual mode**
Policy: append to the end of the list. No merge logic, no "insert alphabetically among the unordered ones" — the operator repositions manually if they care. 

**4. Files removed from Manual mode's stored order**
Drop them from the applied order silently (their row/entry can be pruned or just ignored — doesn't matter which, since it's regenerated on next reorder anyway).

**5. Renamed/moved files**
Since persistence is filename-keyed (matching the rest of the app's existing pattern — thumb, mediaOptions), a rename is indistinguishable from "old file removed + new file added." Under rule #3/#4 that means a renamed file falls to the end of the list post-rename. Acceptable as a known limitation, but worth stating explicitly to the programmer and product owner rather than leaving it implicit — it's a real UX papercut (operator renames a file mid-arrangement, loses its position) even if it's no longer a hard design problem.

[I think this is an acceptable tradeoff for simplicity]

**6. Mode switching**
- Automatic → Manual: seed the stored order from the current alpha-sorted arrangement, so the user starts repositioning from a sensible baseline rather than an empty/undefined list.
- Manual → Automatic: just stop reading the stored order; don't delete it, so flipping back to Manual later restores the prior arrangement.

**7. Live reload / FileSystemWatcher interaction**
In Manual mode, LoadMediaItems() should still diff adds/removes (existing logic in ComputeMediaChanges) but must not call the alpha-SortMediaItems() path — new items get appended (#3), removed items get dropped (#4), everything else keeps its manual position.

**8. Invariants to preserve in both modes**
Blank-screen item pinned to index 0, and TruncateMediaItemsToMaxCount() cap — both need to keep applying after a manual reorder, same as today.

**9. UI mechanics**
Reuse OnlyMSlideManager's existing drag-reorder implementation (drop-zone-per-item + ReorderMessage + ObservableCollectionSuppression rebuild — DragAndDropServiceCustom.cs, MainViewModel.cs:786) rather than designing from scratch; it's a near-direct fit for OperatorPage's ListBox. Drag handles/reorder UI should probably only be interactive when Manual mode is active, to avoid implying you can drag in Automatic mode.

[this is just a reference to some drag/drop code that already exists and might be used as an example]

**10. Settings & docs**
Expose the mode toggle somewhere sensible (per-folder setting seems more correct than global, given #2) and update the wiki's "sorted alphabetically... no provision for reordering" statement once shipped.

**Comment by robertkjr3d** [comment]
I was first seeing where to hang the UI:
<img width="1115" height="830" alt="Image" src="https://github.com/user-attachments/assets/1ac876b6-7dc6-408d-b52d-70a44257c748" />
and seeing if you had the same types of ideas, that could be approved. Mr. Claude was right on track in thinking that yes the code would need to be in either Auto or Manual mode, and it also saw the future in that they would want to be able to move the items up and down in the list.
The SQLLite, this part confused me, and I asked the AI to look into that as well. Since it stores cached data, it could be an issue, but I'm not sure, yes it would be nice to keep from touching that. It would seem that the cacheing is not anything to do with the ordering, but I guess I'll cross that bridge when I hit the Chickens crossing the road.
Of course if the Blank-Screen item is on, yes it would need to remain as item 0...

**Comment by AntonyCorbett** [comment]
Thanks, Robert. I'd prefer to see the sorting mode selection UI in Settings in order to keep the main window as simple as possible.

I'm not sure we would have a date mode. The current calendar mode works automatically, folding in the relevant media items based on date, but still sorting them alphanumerically. I believe the choice is binary - _alphanumeric_ or _manual_.

Regarding manual sorting, I would prefer to use drag-and-drop only. If we _do_ require a keyboard method or command button, we need the notion of a "current item", which we don't have.

Regarding storing a manual order, I suggest we store it not in the database, but in the settings (as we currently do for RecentlyUsedMediaFolders

**Comment by robertkjr3d** [comment]
>>"I'm not sure we would have a date mode. The current calendar mode works automatically, folding in the relevant media items based on date, but still sorting them alphanumerically. I believe the choice is binary - alphanumeric or manual."
I'm not familiar with all of this. When using Only-M... Generally users I've taught have named items 001, 002, or some fashion to cause things to be in the correct order. In Explorer, you can order by Date-Modified, or other things, but Only-M at least in the past only pays attention to the name. Have I missed a change, or is there some setting I've missed?

**Comment by AntonyCorbett** [comment]
Sorry, I thought you were suggesting a new sort mode by date. We don't have one at the moment, and I don't think we should include one. I did make reference to a feature in OnlyM called "calendar folders" (see the Wiki), but this is only date-related in the sense that media items are selectively included in OnlyM based on the current date. However, sorting is always strictly alphanumeric.

**Comment by robertkjr3d** [comment]
I definitely was suggesting a sort made by file-date. When you see it in your folder view, what order do you see? either by name or modified. Up and Down arrows. (you can order by other odd ones) but I believe a normal user-Friendly concept would be by modified date. 
The picture is an example... VLC or Windows Explorer

<img width="1982" height="753" alt="Image" src="https://github.com/user-attachments/assets/074dfc5c-d6b4-4970-a619-5f7d3799fd00" />
If you don't want this change that's fine, I'll just focus on the auto/manual. And just keep the alpha for auto.

**Comment by robertkjr3d** [comment]
I think sortmode would go in settings, but the persistent sorted items needs to be in the SQLLite. As I examined it. It is true that both could be in Settings, but I think its a smarter more maintainable approach to go with the SQLLite. And the proper separation of what goes where. Sort-Mode is a 'setting', and the other is something that will needs persisting, and is not a 'setting'.

**Comment by robertkjr3d** [comment]
Practical impact on DB Schema upgrade:
•	first run after update may feel “cold” (thumbnails regenerate)
•	any DB-only user preferences/history are reset (not Settings)
If you want to avoid this, next step is schema migration logic (ALTER/create-if-missing) instead of delete/recreate on version mismatch.
But I didn't think it would be a big deal, unless you thought it would be.
