### ISSUE TITLE
Instability Issues

### ISSUE THREAD

**Issue by athornfam2** [AntonyCorbett/OnlyM#387]
**Describe the bug**
During the meetings... we've noticed that OnlyM freezes at random times which stops us from displaying media over Zoom. The only fix, naturally, is to shut the program down from task manager and then reopen it which does work but can be tough for non-IT AV brothers to navigate during the meeting quickly.

**To Reproduce**
- This cannot be easily reproduced but typically adding media (both pictures and videos) are only what we are doing usually all in 720p or less. Settings can be screencapped and any log files can be attached

**Screenshots**
- None at the moment; OnlyM does not output any errors.

**Desktop (please complete the following information):**
 - Windows 10 1909 to 21h2
 - Systems vary from Quad to Hex core systems, 8-16gb of ram, all on SSD/M.2

**Comment by AntonyCorbett** [comment]
@athornfam2 This is likely the media foundation bug that affects video rendering on a secondary screen. Discussed elsewhere in this project.

Regards
Antony

**Comment by athornfam2** [comment]
Any chance of this being fixed?

**Comment by AntonyCorbett** [comment]
@athornfam2 Some background:

There is a known issue in .NET Framework, which MS describes as "a synchronization issue between WPF and the underlying WMP control have to resynchronize when the display changes occur." It happens to H.264 codec video files (MP4).

In my experience it It only seems to affect some video cards. In OnlyM there are several workarounds (none ideal):

1. Use full-screen mode (rather than windowed mode) for the media window. This works on secondary display because OnlyM overlaps 1 pixel on to the primary display.
2. Always place the media window on the primary display.
3. Select "FFMPEG" rendering (in Settings).
4. Turn off hardware acceleration using OnlyM's -nogpu command-line option (but this usually results in poor playback).
5. Disable the media foundation codec in Windows and find another one to support MP4.

I will eventually port the project to .NET 5 and use a different rendering control.

Regards
Antony

**Comment by AntonyCorbett** [comment]
@athornfam2 I have ported the project to .NET 5 and would like to determine if this long standing Media Foundation bug has been fixed. Please let me know if you would be willing to test (unfortunately, I don't have machines on which I can replicate the issue).

**Comment by athornfam2** [comment]
Yes I would like to test.

Thanks,

Matthew Wolf

**Comment by AntonyCorbett** [comment]
@athornfam2 Please download and install the latest pre-release (v2.0.0.1). If you later want to revert to the standard release please uninstall OnlyM first. 

This version is built using .NET 5 and there are many changes in the code and framework. I hope that MS have given attention to the bug described above, but I have my doubts. If issues remain, I will attempt to integrate VLC for video rendering.

Thanks for your help.

**Comment by athornfam2** [comment]
@AntonyCorbett 

I've installed the Pre-Release version of OnlyM. I'll see if we can use it at our meetings to test out as we have a backup AV attendant at all times. I'll let you know my findings in about 1-2 weeks. Do you need any logs or system performance reports from the app?

**Comment by AntonyCorbett** [comment]
@athornfam2 Thanks for your help. I don't need any further information; I hope it should be fairly easy to detect whether the issue remains.

**Comment by athornfam2** [comment]
@AntonyCorbett Wanted to follow up on this request. The .NET application has been working well. No issues on my end with the past meetings.

**Comment by AntonyCorbett** [comment]
@athornfam2 thanks for the useful feedback. You know what will happen at the next meeting - right :)
