### ISSUE TITLE
Default media folder someplace other than documents.

### ISSUE THREAD

**Issue by omaha4** [AntonyCorbett/OnlyM#42]
One thing I just realised is that by placing the default media folder in Documents, OneDrive is by default syncing this folder to the cloud. Besides this not being ideal, this may slow down the KH internet connection for auditoriums with slower connection speeds. Short of switching to a playlist system (which is the gold standard, especially after using Playback Pro) perhaps a new folder could be created just below the /user/"defaultuser" level, default user being the active user account.

One retort to this that a user could simply just change the OneDrive sync settings so that the media folder is being excluded from the sync. True, but how many individuals on setup would remember to do this?

**Comment by AnsNie** [comment]
Although I am not against the idea, which is ok for me (default folder being there), I have to comment that I assume that most of KH's use an offline Windows account, so that Onedrive is not active. And if someone wants to use Onedrive, they should separately specify, which folders they want to sync. Also I think that LDC does the installations in many branches, and at least will do at some point, so that they will do all the setups using the same standards.
Just some thoughts on why I find this a minor problem. I don't take a stand on whether or not the default folder should be changed.

**Comment by AntonyCorbett** [comment]
@omaha4 Thanks for feedback. Documents is the natural storage location, and as you know, you can change the folder in the Settings page.
