### ISSUE TITLE
Decreased video saturation in Media Foundation mode

### ISSUE THREAD

**Issue by AntonyCorbett** [AntonyCorbett/OnlyM#45]
Some have observed that videos are rendered with decreased saturation (i.e. appear "washed out") when played using the "Media Foundation" engine (see Settings page). This is only seen on certain video cards.

Please make sure you have the correct and latest video driver installed. 

One suggestion (if you have an NVidia card) is to go to the NVidia control panel. Click on "Video" in the options tree. Select the monitor and click the "With NVidia Settings" radio button. In the advanced tab, select "Dynamic Range 0-255".

**Comment by Blann** [comment]
Not sure if I’m being overly pedantic about it but I would say it’s definitely more of a brightness/contrast thing rather than saturation – if anything saturation appears decreased. If the first frame of the video is black (as is the case with most videos from jw.org) then it’s instantly identifiable because the background goes from black to dark grey.

Regarding whether the issue is present when using MF in SoundBox – it is.

The PC at our KH has an Nvidia card, but I have tested on another machine with an AMD card and the issue is also present there. I changed the pixel format from the default YCbCr 4:4:4 to RGB 4:4:4 (equivalent to the step you mention for Nvidia cards) but this did not solve the problem (reluctant to call it that as it’s relatively minor in the grand scheme of things – it’s just difficult to unsee for someone like me!)

**Comment by AntonyCorbett** [comment]
@Blann my fault - I should have said _decreased_ saturation. I will modify the title accordingly.

**Comment by Blann** [comment]
Not sure if it’s any help but it just occurred to me that I think JWL uses Media Foundation to render videos as well (at least, when I have globally disabled Media Foundation, videos have failed to play in JWL), but this issue is not present there.

**Comment by AntonyCorbett** [comment]
@Blann thanks. And can you confirm that the ffmpeg engine renders ok?

**Comment by Blann** [comment]
Yes. The Windows Media Player and VLC options in SoundBox also render correctly. Just Media Foundation where this is in evidence.

**Comment by Blann** [comment]
![onlym-capture-001](https://user-images.githubusercontent.com/39594788/44609212-aa899b00-a7ee-11e8-806c-e8f1db7dc205.jpg)
Was able to capture it - top is ffmpeg, bottom is Media Foundation.

**Comment by AntonyCorbett** [comment]
Closing because there is nothing more I can do with this.
