### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by Altdawidf4** [AntonyCorbett/OnlyM#478]
**Describe bug** Windows 11 I have problem with taskbars **For Reproduction*when I click on images/video the winows bar is used for 0.5 seconds and only illustration and the same as I disable illustrations

**Expected behavior** I made the illustrations flow smoothly without dimming the screen
Windows 11 version

plz help me

**Comment by AntonyCorbett** [comment]
@Altdawidf4 if I understand you correctly, when you click the **Play** button in OnlyM in order to display an image, for example, the image is shown on the media monitor but only after the taskbar is momentarily shown. Is that right? 

Can you provide more information to help me understand exactly what is happening, please?

**Comment by Altdawidf4** [comment]
exactly

**Comment by AntonyCorbett** [comment]
@Altdawidf4 I'm sorry, I can't reproduce the problem you describe. Would it be possible to send a short video showing what happens, please?

**Comment by AntonyCorbett** [comment]
Closing as no response. @Altdawidf4 - please reopen if needed.
