### ISSUE TITLE
Folder/Shortcut support

### ISSUE THREAD

**Issue by ucphinni** [AntonyCorbett/OnlyM#53]
Folders nested within the OnlyM media folder could be rendered within the UI.  This would greatly help with organization.

Using the aforementioned feature, shortcuts may be used in order to save space between folders.

Day 1 , this might be treated as an advanced feature and would be done at the file system level.  Navigation (up & down hierarchy) of the folder in the OnlyM UI would have to be implemented.

**Comment by AntonyCorbett** [comment]
@ucphinni thanks for yoru suggestion. Please would you provide an example of how this would help you? Thanks, Antony

**Comment by ucphinni** [comment]
Thank you for responding so quickly. 
At our kingdom hall, we have 4 congregations that use the auditorium.
Examples:
• The first congregation stores the CO Visit’s media in OnlyV (Sometimes 4 or 5 months in advance) 
• Congregation puts their local needs pictures in advance. 
• Bethel Speaker visits.  Have seen 8 to 12 pictures sitting in the list that only the hosting congregation can use.  Could used a folder, then a nested folder for each day with the picture items.
• At least one Congregation pre-load images that they get from public speaker into onlyV up to a week in advance.

Shortcut feature can be used to organize as well as for space efficiency.  I do not have a current use case but this is one possible example.
• At the OnlyV top level, a folder per congregation + folder for standard midweek + extras folder.  In each congregation folder, a shortcut to midweek folder. Each congregation would select their folder and play media from there and delete their files/shortcuts.  The administrator would copy to the extras files such as regional review and link it into the congregation folders on demand which each congregation can delete when no longer needed.

**Comment by AntonyCorbett** [comment]
@ucphinni I wonder whether you can solve all of these issues using the "id" command-line option and the "calendar folder" support?

**Comment by Blann** [comment]
Seems like a lot of your issue could be solved by having different instances for the different congregations using the ‘id’ option, as Antony said. Each congregation would then at least only see what’s relevant to them.

**Comment by ucphinni** [comment]
Regarding soundbox, yes we did use it, but only 2 out of the 4 congregations used it.  The other 2 would use vlc, Windows Media Player, Windows Photos, etc.  There were 2 administrators of this list, 1 for each congregation and they communicated and collaborated..  When/if someone called an adminstrator during their meeting for tech support, the contacted administrator always had to figure out what the current state of the system and what apps they were using.  Making everyone use the same apps eliminates the later and simplifies training.

Within the past year, we lost 1 administrator leaving myself and so I moved all 4 congregations  to OnlyT & M for unity and simplicity.  Tech calls have frequency have diminished and when they do happen, I know whats going on and can get them up and running quickly.

I am playing with the id now with my congregation.  I will deploy it to the others if it works out.

**Comment by DanJermy** [comment]
Adding our use case in to see if this is an enhancement that should/could be considered or if I should consider an alternative approach (apologies in advance for the long post)...

It also raises the larger question I'm currently assessing which I would appreciate some input on - **Should we have separate windows logins for each congregation?**

We have 2 congregations (plus a group that meets separately on occasion) that share the hall, and with our previous PC build using SoundBox we had separate windows logins separating configuration for soundbox (though I know that could have been done with soundbox presenting a list on launch), as well as for KHconf (which can also support multiple congs through a list), however we had dropbox synching with different accounts and the clear delineation of a windows account (with different PINs) made user error in selecting wrong config more unlikely (some soundbox config selected by each cong varied).

As part of the new W10 build with JWL in the brave new world, we've set up a folder structure in a single OneDrive account to store Recordings (with cong subfolder) and allow Uploading of media by any of our brothers in advance of the meetings - also in subfolders.

@AntonyCorbett  I notice your suggestion of the use of the 'id' parameter; and so far I've used the 'source' option under separate shortcuts for each congregation, as well as a third for a 'shared' folder where content might be needed by both congregations (i.e. for a local needs video for all congs rather than a picture for a public talk to be shown for just one cong)...  However, this will result in 3 desktop shortcuts for **OnlyM** alone!

I could do the same with **OnlyR** although I'd need to use additional folder junctions to redirect to the OneDrive path.  Alternatively it would be ideal if **OnlyR** could use a different folder path based on the time (as suggested in an existing feature request, such that it would use the timings set for the countdown timer in OnlyT).

**OnlyV** don't really require cong-specific config at this stage; **OnlyT** can accommodate multiple congs countdown timer already which is sufficient (although I could see opinions dividing on some of the other options); so I just need to determine the merits of separate logins for clarity (i.e. single icons to launch **OnlyM** and **OnlyR** with default paths being set, along with potential future scalability) _vs_ a single login which can be more consistent across both congregations.

If functionality was available to present a cong menu for each app or allow to be auto-selected by the time of day (and later overridden if necessary) then having a single login for all congs would seem more straight forward.  Would having an independent "OnlyConfig" app that the other apps reference to set these times and default folder locations defeat the purpose of separating the apps out?

Apologies for rambling nature of this post; hopefully enough to give folks a background on requirements such that I can pilfer the no-doubt well thought out implementations of other fellow KH techies out there.  Likely I'm over-complicating it, so help me to introduce the KISS principle where it applies.

Thanks in advance / Dan

_ps. bonus question - {Not sure if there's a more appropriate forum to ask overarching questions beyond the scope of an individual app or ones that are to do with JWL operation, but may I ask} Do most people use a standard account rather than an admin one for day to day Sound Desk operations?_

**Comment by Pickles-The-Cat** [comment]
Dan,

We have 4 congregations (3 English speaking, one Polish speaking) at our KH. 

I have separate User Accounts set up for each Cong in our Windows 10 set up. 

We have a couple of brothers that  have the admin password but we don’t publish this out as too many different people fiddling with things tends to lead to disaster in the end (I have experienced this before!). 

It tends to work OK, apart from I need to do some installs 4 times, and remember what the settings are for each Cong, but it does allow some degree of customisation for the different congs dependant on how they want to do things. 

Also if something does break due to the usage of the hall it’s hard to find a time (most weekdays a meeting is in held) to fix things, so having a separate account for the next Cong, allows most software issues to hold till I can get in and fix before their next meeting. 

Thanks

Mike
