### ISSUE TITLE
Monitor labels can't be changed | List ambiguously shows 2x "Generic PnP Monitor"

### ISSUE THREAD

**Issue by DanJermy** [AntonyCorbett/OnlyM#64]
![onlym monitor naming issue](https://user-images.githubusercontent.com/44350333/47274103-628db700-d598-11e8-8b9a-fef1b4829d84.png)

{Once again many thanks to all those who've produced an exceptionally helpful tool; we're currently attempting a migration from Soundbox}

Within Soundbox there was the capability to change the 'names' (i.e. labels) of the monitors. This seems to rely on windows now, and it's proving challenging to rename them through driver installs etc. I've managed to have one update but the others (esp. the one that runs to the HDMI to SDI converter just show 'Generic PnP Monitor' - so it's impossible to distinguish between the timer screen and the TV displays.  Even using the registry hack to use the 'friendly name' string doesn't modify their name in any of the Only_ apps, even though it does successfully change it inside Device Manager.

Is this something that can easily be worked around or does it require new functionality to be written in?

Many thanks again / Dan

**Comment by Pickles-The-Cat** [comment]
Antony,

I’d like to see this feature as well.

We have 4 Cong’s using a desktop PC that has a touch screen monitor for the SoundDesk, linked to a HDMI splitter at the front of the hall supporting the two Platform TV’s and then a third screen doing the timing. 

When we need to select the screen in OnlyM we are presented with 3 "Generic PnP Monitor" options and if the operator picks the wrong one, he will get the Image displayed on the SoundDesk touch screen monitor and because we don’t have a keyboard there is no way to bring up the onscreen keyboard and hence the only option left is to re-boot the system. 

2 of Cong’s had this issue this weekend..  

If we had this function to name the monitors (like we did in Soundbox) then that would be great. 

I also assume that updating the OnlyM software version requires a reset of the monitor to use? 

Thanks

Mike

**Comment by AntonyCorbett** [comment]
@Pickles-The-Cat >I also assume that updating the OnlyM software version requires a reset of the monitor to use? <

No, it retains the settings

**Comment by TizianoNoto** [comment]
@AntonyCorbett [Here on Stack Overflow](https://stackoverflow.com/questions/4958683/how-do-i-get-the-actual-monitor-name-as-seen-in-the-resolution-dialog) i read that making the proper calls to `EnumDisplayDevices` will let you get the real device name (as seen in Control Panel) from `DisplayDevice.DeviceString`. I'm still slowly learning c# but I'll see if I can test this myself.

**Comment by AntonyCorbett** [comment]
@TizianoNoto Thanks for your help. I suspect it's not so simple but would welcome any assistance.

**Comment by Pickles-The-Cat** [comment]
Anthony,

Thanks. however it doesn’t seem to be happening this way at our KH. OnlyM seems to loose the setting ever few weeks or so. 

Could this be windows update causing this issue? 

Any suggestions as to why this would be happening would be appreciated. 

It’s just really causing issues for the brothers using the sounddesk..

Thanks

Mike

**Comment by AntonyCorbett** [comment]
@Pickles-The-Cat This may happen if the monitors are not left on stand-by or if they are switched on after OnlyM loads. If the monitor info is not available when OnlyM loads then it will not be able to select the monitor. If you can't leave monitors on stand-by then you may want to use an EDID emulation device.

**Comment by Pickles-The-Cat** [comment]
Antony,

Thanks.. EDID emulators now ordered, as well as big sign for the KH PC stating “Turn the Screens ON before booting up the PC”!!! (which I think is the error despite my advising of this in the training I did!!).

Thanks for your support on this one..

Mike

**Comment by AntonyCorbett** [comment]
Fixed in 1.1.0.5

**Comment by DanJermy** [comment]
Thanks so much for this Antony et al.  Much appreciated and phenomenal turn-around!
Would love it if this could get added to OnlyV and OnlyT also :)

**Comment by AntonyCorbett** [comment]
@DanJermy Already in OnlyT pre-release. Will add to OnlyV soon

**Comment by TizianoNoto** [comment]
Glad to see the thread I linked was actually useful.
