### ISSUE TITLE
TO be able to change permanent backdrop from black to a .jpeg/.pdf

### ISSUE THREAD

**Issue by PowellGeoff** [AntonyCorbett/OnlyM#96]
Recently we wanted to use onlyM at our circuit assembly, but as the CO wanted to display a custom backdrop on the screen (based on the printed program), we could not elegantly use onlyM, as when onlyM retakes control from JW Library, it defaults to the black screen. Can the option be included, not only black permanent screen, but also custom?
Thanks,
Geoff

**Comment by AntonyCorbett** [comment]
@PowellGeoff Could you just add the image to the media list and then display it as and when needed?

**Comment by blazer2004** [comment]
You could make the image you wanted to show the desktop back ground on an extended desktop.

**Comment by AntonyCorbett** [comment]
@PowellGeoff I don't think I would consider distorting images and videos just to fill a screen.

**Comment by TizianoNoto** [comment]
@PowellGeoff We use TimePlayer in our KH. There is an option to adjust the margins like OnlyM but not for expanding pictures, so what you say is not supposed to happen. 

@blazer2004 Why not JWL? It's been used for a while in my area when places are rented for memorials or circuit assemblies and I never noticed any problems.

**Comment by blazer2004** [comment]
@TizianoNoto We use JWL for the Memorial, and memorials and for many other things too. But for more complicated scenarios, a playlist is one of a media operators best friends. For an assembly why not make it simple on the media operator, and playlist the morning or afternoon so he doesn't worry about very much. It's a small thing, but small things add up, especially when you know you have that many people depending on you :) 

@PowellGeoff I can't help to wonder if the projectors that are being used are 16:10 (768p)? Have you ever tried running the extended desktop for JWL at 16:10, which many projectors are, instead of 16:9? JWL produces a black border around the video. That would explain why other programs are scaling the media to size, and JWL is not, especially if the PC is going straight to the projector, and not a video switch running at 720p or 1080p. Not that there is anything wrong with 16:10. If you notice in person or on the videos, many of the video walls used at conventions are 16:10, not 16:9. Its a design consideration to be taken into account.

**Comment by TizianoNoto** [comment]
@blazer2004 I get what you're saying. If a video system is available the only media shown in circuit assemblies are songs lyrics and watchtower study's pictures which you can easily handle with JWL. For bigger events, e.g. regional conventions, the italian branch has dedicated equipments for audio and video control. I've never asked what software runs in those, though.

**Comment by AntonyCorbett** [comment]
@PowellGeoff I'll close this issue for now since it seems that a bespoke desktop image would work well.

**Comment by JohannesKreuzer** [comment]
@TizianoNoto the Audio and Video Systems provided by RBD Europe (these systems are used all over Europe at regional conventions, but some branches have own systems) are using VLC Player for media playback.

**Comment by PowellGeoff** [comment]
Thanks for all your input!
